app_3/app_3/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static 


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('main.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     urlpatterns.append(path('static/<path:path>', never_cache(serve)))

app_3/main/urls.py
from django.urls import path, include
from .views import *


app_name = 'main'
urlpatterns = [
    path('service/', service, name='service'),
    path('home/', index, name='index'),
    path('about/', about, name='about'),
    path('', home, name='home'),
    path('contact/', contact, name='contact' )
]

app_3/main/models.py
from django.db import models

class Image(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='imgs/')

    def __str__(self):
        return self.title

app_3/main/forms.py
from django import forms
from .models import Image

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'image')

class ContactForm(forms.Form):
    full_name = forms.CharField(max_length=50)
    email_address = forms.EmailField(max_length=150)
    subject = forms.CharField(max_length=50)
    message = forms.CharField(widget=forms.Textarea, max_length=2000)

app_3/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from .models import *
from .forms import *
from django.core.mail import send_mail, BadHeaderError
# Create your views here.

def index(request):
    persons = Image.objects.order_by('-title')
    context = {'persons': persons}
    return render(request, "main/index.html", context=context)

def about(requset):
    persons = Image.objects.order_by('-title')
    context = {'persons': persons}
    return render(requset, "main/about.html", context=context)

def home(request):
    return redirect("http://localhost:8000/home/")

def service(request):
    return render(request, "main/service.html")

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = "Website Inquiry"
            body = {
                'full_name': form.cleaned_data['full_name'],
                'email_address': form.cleaned_data['email_address'],
                'subject': form.cleaned_data['subject'],
                'message': form.cleaned_data['message'],
            }
            message = "\n".join(body.values())

            try:
                send_mail(subject, message, 'eriklevonyan0@gmail.com', ['eriklevonyan0@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found')
            return redirect("http://localhost:8000/home/")
    form = ContactForm()
    return render(request, "main/contact.html", {'form': form})

app_3/main/templates/main/about.html
{% extends "main/index.html" %}

{% load bootstrap5 %}
{% load static %}
{% block title %}ABOUT{% endblock %}
{% block content %}

   <!-- Page Header Start -->
   <div class="container-fluid bg-dark p-5">
    <div class="row">
        <div class="col-12 text-center">
            <h1 class="display-4 text-white">About Us</h1>
            <a href="{% url 'main:home' %}">Home</a>
            <i class="far fa-heart text-primary px-2"></i>
            <a href="{% url 'main:about' %}">About</a>
        </div>
    </div>
</div>
<!-- Page Header End -->


<!-- About Start -->
<div class="container-fluid bg-secondary p-0">
    <div class="row g-0">
        <div class="col-lg-6 py-6 px-5">
            <h1 class="display-5 mb-4">Welcome To <span class="text-primary">CONSULT</span></h1>
            <h4 class="text-primary mb-4">Diam dolor diam ipsum sit. Clita erat ipsum et lorem stet no lorem sit clita duo justo magna dolore</h4>
            <p class="mb-4">Et stet ipsum nonumy rebum eos justo, accusam invidunt aliquyam stet magna at et sanctus, vero sea sit amet dolores, sit dolor duo invidunt dolor, kasd rebum consetetur diam invidunt erat stet. Accusam nonumy lorem kasd eirmod. Justo clita sadipscing ea invidunt rebum sadipscing consetetur. Amet diam amet amet sanctus sanctus invidunt erat ipsum eirmod.</p>
            <a href="" class="btn btn-primary py-md-3 px-md-5 rounded-pill">Get A Quote</a>
        </div>
        <div class="col-lg-6">
            <div class="h-100 d-flex flex-column justify-content-center bg-primary p-5">
                <div class="d-flex text-white mb-5">
                    <div class="d-flex flex-shrink-0 align-items-center justify-content-center bg-white text-primary rounded-circle mx-auto mb-4" style="width: 60px; height: 60px;">
                        <i class="fa fa-user-tie fs-4"></i>
                    </div>
                    <div class="ps-4">
                        <h3>Business Planning</h3>
                        <p class="mb-0">Tempor erat elitr rebum at clita. Diam dolor ipsum amet eos erat ipsum lorem et sit sed stet lorem sit clita duo</p>
                    </div>
                </div>
                <div class="d-flex text-white mb-5">
                    <div class="d-flex flex-shrink-0 align-items-center justify-content-center bg-white text-primary rounded-circle mx-auto mb-4" style="width: 60px; height: 60px;">
                        <i class="fa fa-chart-line fs-4"></i>
                    </div>
                    <div class="ps-4">
                        <h3>Financial Analaysis</h3>
                        <p class="mb-0">Tempor erat elitr rebum at clita. Diam dolor ipsum amet eos erat ipsum lorem et sit sed stet lorem sit clita duo</p>
                    </div>
                </div>
                <div class="d-flex text-white">
                    <div class="d-flex flex-shrink-0 align-items-center justify-content-center bg-white text-primary rounded-circle mx-auto mb-4" style="width: 60px; height: 60px;">
                        <i class="fa fa-balance-scale fs-4"></i>
                    </div>
                    <div class="ps-4">
                        <h3>legal Advisory</h3>
                        <p class="mb-0">Tempor erat elitr rebum at clita. Diam dolor ipsum amet eos erat ipsum lorem et sit sed stet lorem sit clita duo</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- About End -->


<!-- Team Start -->
<div class="container-fluid py-6 px-5">
    <div class="text-center mx-auto mb-5" style="max-width: 600px;">
        <h1 class="display-5 mb-0">Our Team Members</h1>
        <hr class="w-25 mx-auto bg-primary">
    </div>
    <div class="row g-5">
        {% include 'main/components/team_members.html' %}
    </div>
</div>
<!-- Team End -->

{% endblock %}

app_3/main/templates/main/components/services.html
<div class="container-fluid py-6 px-5">
    <div class="text-center mx-auto mb-5" style="max-width: 600px;">
        <h1 class="display-5 mb-0">What We Offer</h1>
        <hr class="w-25 mx-auto bg-primary">
    </div>
    <div class="row g-5">
        <div class="col-lg-4 col-md-6">
            <div class="service-item bg-secondary text-center px-5">
                <div class="d-flex align-items-center justify-content-center bg-primary text-white rounded-circle mx-auto mb-4" style="width: 90px; height: 90px;">
                    <i class="fa fa-user-tie fa-2x"></i>
                </div>
                <h3 class="mb-3">Business Research</h3>
                <p class="mb-0">Tempor erat elitr rebum at clita. Diam dolor ipsum amet eos erat ipsum lorem et sit sed stet lorem</p>
            </div>
        </div>
        <div class="col-lg-4 col-md-6">
            <div class="service-item bg-secondary text-center px-5">
                <div class="d-flex align-items-center justify-content-center bg-primary text-white rounded-circle mx-auto mb-4" style="width: 90px; height: 90px;">
                    <i class="fa fa-chart-pie fa-2x"></i>
                </div>
                <h3 class="mb-3">Stretagic Planning</h3>
                <p class="mb-0">Tempor erat elitr rebum at clita. Diam dolor ipsum amet eos erat ipsum lorem et sit sed stet lorem</p>
            </div>
        </div>
        <div class="col-lg-4 col-md-6">
            <div class="service-item bg-secondary text-center px-5">
                <div class="d-flex align-items-center justify-content-center bg-primary text-white rounded-circle mx-auto mb-4" style="width: 90px; height: 90px;">
                    <i class="fa fa-chart-line fa-2x"></i>
                </div>
                <h3 class="mb-3">Market Analysis</h3>
                <p class="mb-0">Tempor erat elitr rebum at clita. Diam dolor ipsum amet eos erat ipsum lorem et sit sed stet lorem</p>
            </div>
        </div>
        <div class="col-lg-4 col-md-6">
            <div class="service-item bg-secondary text-center px-5">
                <div class="d-flex align-items-center justify-content-center bg-primary text-white rounded-circle mx-auto mb-4" style="width: 90px; height: 90px;">
                    <i class="fa fa-chart-area fa-2x"></i>
                </div>
                <h3 class="mb-3">Financial Analaysis</h3>
                <p class="mb-0">Tempor erat elitr rebum at clita. Diam dolor ipsum amet eos erat ipsum lorem et sit sed stet lorem</p>
            </div>
        </div>
        <div class="col-lg-4 col-md-6">
            <div class="service-item bg-secondary text-center px-5">
                <div class="d-flex align-items-center justify-content-center bg-primary text-white rounded-circle mx-auto mb-4" style="width: 90px; height: 90px;">
                    <i class="fa fa-balance-scale fa-2x"></i>
                </div>
                <h3 class="mb-3">legal Advisory</h3>
                <p class="mb-0">Tempor erat elitr rebum at clita. Diam dolor ipsum amet eos erat ipsum lorem et sit sed stet lorem</p>
            </div>
        </div>
        <div class="col-lg-4 col-md-6">
            <div class="service-item bg-secondary text-center px-5">
                <div class="d-flex align-items-center justify-content-center bg-primary text-white rounded-circle mx-auto mb-4" style="width: 90px; height: 90px;">
                    <i class="fa fa-house-damage fa-2x"></i>
                </div>
                <h3 class="mb-3">Tax & Insurance</h3>
                <p class="mb-0">Tempor erat elitr rebum at clita. Diam dolor ipsum amet eos erat ipsum lorem et sit sed stet lorem</p>
            </div>
        </div>
    </div>
</div>

app_3/main/templates/main/components/team_members.html
{% for person in persons %}
<div class="col-lg-4">
    <div class="team-item position-relative overflow-hidden">
        <img class="img-fluid w-100" src="{{person.image.url}}" alt="">
        <div class="team-text w-100 position-absolute top-50 text-center bg-primary p-4">
            <h3 class="text-white">{{ person.title }}</h3>
            <p class="text-white text-uppercase mb-0">Designation</p>
        </div>
    </div>
</div>
{% endfor %}

app_3/main/templates/main/contact.html
{% extends "main/index.html" %}

{% load bootstrap5 %}
{% load static %}
{% block title %}CONTACT US{% endblock %}
{% block content %}


    <!-- Page Header Start -->
    <div class="container-fluid bg-dark p-5">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="display-4 text-white">Contact Us</h1>
                <a href="">Home</a>
                <i class="far fa-heart text-primary px-2"></i>
                <a href="">Contact</a>
            </div>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- Contact Start -->
    <div class="container-fluid bg-secondary px-0">
        <div class="row g-0">
            <div class="col-lg-6 py-6 px-5">
                <h1 class="display-5 mb-4">Contact For Any Queries</h1>
                <form method="POST">
                    {% csrf_token %}
                    {% bootstrap_form form layout="horizontal" %}                    

                    <div class="row g-3">
                        <div class="col-6">
                            <div class="form-floating">
                            </div>
                        </div>
                        <div class="col-12">
                            <button class="btn btn-primary w-100 py-3" type="submit">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-6" style="min-height: 400px;">
                <div class="position-relative h-100">
                    <iframe class="position-relative w-100 h-100"
                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3001156.4288297426!2d-78.01371936852176!3d42.72876761954724!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4ccc4bf0f123a5a9%3A0xddcfc6c1de189567!2sNew%20York%2C%20USA!5e0!3m2!1sen!2sbd!4v1603794290143!5m2!1sen!2sbd"
                        frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->


{% endblock %}

app_3/main/templates/main/service.html
{% extends "main/index.html" %}

{% load bootstrap5 %}
{% load static %}
{% block title %}SERVICE{% endblock %}
{% block content %}


<div>
    <!-- Page Header Start -->
    <div class="container-fluid bg-dark p-5">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="display-4 text-white">Services</h1>
                <a href="{% url 'main:home' %}">Home</a>
                <i class="far fa-heart text-primary px-2"></i>
                <a href="">Services</a>
            </div>
        </div>
    </div>
    <!-- Page Header End -->
    

    <!-- Services Start -->
    {% include 'main/components/services.html' %}
    <!-- Services End -->

    <!-- Quote Start -->
    <div class="container-fluid bg-secondary px-0">
        <div class="row g-0">
            <div class="col-lg-6 py-6 px-5">
                <h1 class="display-5 mb-4">Request A Free Quote</h1>
                <p class="mb-4">Kasd vero erat ea amet justo no stet, et elitr no dolore no elitr sea kasd et dolor diam tempor. Nonumy sed dolore no eirmod sit nonumy vero lorem amet stet diam at. Ea at lorem sed et, lorem et rebum ut eirmod gubergren, dolor ea duo diam justo dolor diam ipsum dolore stet stet elitr ut. Ipsum amet labore lorem lorem diam magna sea, eos sed dolore elitr.</p>
                <form>
                    <div class="row gx-3">
                        <div class="col-6">
                            <div class="form-floating">
                                <input type="text" class="form-control" id="form-floating-1" placeholder="John Doe">
                                <label for="form-floating-1">Full Name</label>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-floating mb-3">
                                <input type="email" class="form-control" id="form-floating-2" placeholder="name@example.com">
                                <label for="form-floating-2">Email address</label>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-floating">
                                <select class="form-select" id="floatingSelect" aria-label="Financial Consultancy">
                                    <option selected>Financial Consultancy</option>
                                    <option value="1">Strategy Consultancy</option>
                                    <option value="2">Tax Consultancy</option>
                                </select>
                                <label for="floatingSelect">Select A Service</label>
                            </div>
                        </div>
                        <div class="col-6">
                            <button class="btn btn-primary w-100 h-100" type="submit">Request A Quote</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-6" style="min-height: 400px;">
                <div class="position-relative h-100">
                    <img class="position-absolute w-100 h-100" src="{% static 'main/img/quote.jpg' %}" style="object-fit: cover;">
                </div>
            </div>
        </div>
    </div>
    <!-- Quote End -->

    {% endblock %}